demo:
  flyway:
    migrate: true
    migrate-at-start: true
    locations: db/migration
    baseline-on-migrate: true
    baseline-version: 0
quarkus:
  log:
    level: INFO
    #  hibernate-orm:
    #    database:
    #      generation: drop-and-create
    log:
      sql: true
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
    jdbc:
      timezone: UTC
  datasource:
    db-kind: postgresql
    username: postgres
    password: dafuq@911
    jdbc:
      ~: false
#    jdbc:
#      url: jdbc:postgresql://localhost:5432/postgres?schema=fins
    reactive:
      ~: true
      #      url: postgresql://localhost:5432/my_db?schema=product
      url: postgresql://localhost:5432/postgres?schema=fins
      max-size: 20
#"%prod":
#  quarkus:
#    hibernate-orm:
#      sql-load-script: no-file
#      database:
#        generation: none
