quarkus:
  datasource:
    username: user
    password: password
    reactive:
      url: postgresql://localhost:5432/my_db
      max-size: '20'
    db-kind: postgresql
    jdbc:
      ~: false
      url: jdbc:postgresql://localhost:5432/my_db
  flyway:
    migrate: 'true'
    baseline-on-migrate: 'true'
    locations: db/migration
    migrate-at-start: 'true'
    schemas: product
    baseline-version: '0'
  log:
    level: INFO
    log:
      sql: true
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
    jdbc:
      timezone: UTC
