CREATE TABLE Product
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY,
    createdAt   timestamp,
    description varchar(255),
    title       varchar(255),
    updatedAt   timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE ShoppingCart
(
    id        int8 GENERATED BY DEFAULT AS IDENTITY,
    cartTotal int4 NOT NULL,
    name      varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE ShoppingCartItem
(
    id           int8 GENERATED BY DEFAULT AS IDENTITY,
    quantity     int4,
    total_price  numeric(21, 2),
    cart_id      int8,
    product_id   int8,
    cartItems_id int8,
    PRIMARY KEY (id)
);

CREATE INDEX shopping_cart_item_cart_product_index
    ON ShoppingCartItem (cart_id,
                         product_id);

ALTER TABLE if EXISTS ShoppingCartItem
    ADD CONSTRAINT FKf989tn6tlwy1j1yrx2hs67p5k
    FOREIGN KEY (cart_id)
    REFERENCES ShoppingCart;

ALTER TABLE if EXISTS ShoppingCartItem
    ADD CONSTRAINT FKlwg03ca4l3v3fnymvh7n7db92
    FOREIGN KEY (product_id)
    REFERENCES Product
    ON
DELETE
CASCADE;

ALTER TABLE if EXISTS ShoppingCartItem
    ADD CONSTRAINT FK9uj82nvkymqyihirsw46wr0si
    FOREIGN KEY (cartItems_id)
    REFERENCES ShoppingCart;
